### ISSUE TITLE
Google's Lighthouse reports the following

### ISSUE THREAD

**Issue by mgifford** [YOWCT/yowct.github.io#2]
Color Contrast Is Satisfactory
These are opportunities to improve the legibility of your content.
Background and foreground colors do not have a sufficient contrast ratio.
Low-contrast text is difficult or impossible for many users to read. Learn more.

Failing elements:
```
<a class="navbar-brand page-scroll" href="#home">
<a href="#home">
<a href="#about">
<a href="#events">
<a href="#projects">
<a href="#contact">
<p class="copyright text-muted small">
<a href="http://startbootstrap.com/">
```

**Comment by xander-miller** [comment]
I see the issue, but when you mouse over the nav elements, the contrast increases. In the case of the copyright it should be understated. It would be nice if they recommended a specific threshold.

**Comment by mgifford** [comment]
This tool gives you a recommendation http://contrast-finder.tanaguru.com/

Good if folks can read it before they bring the element into focus.

**Comment by xander-miller** [comment]
Okay I upped the contrast in commit cf8eb3b. I don't have lighthouse installed on this computer but I think it should be fixed. Thank you for sharing that contrast calculation tool. Made the process much more straight forward.

**Comment by mgifford** [comment]
Excellent.
